/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPages;

import static guiapp.Dashboard.dtop;
import guiapp.log;
import guiapp.rep;
import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import side.NewJFrame;
import side.inter;


/**
 *
 * @author ortega
 */
public class bor extends javax.swing.JInternalFrame {

    /**
     * Creates new form bor
     */
    public bor() {
        initComponents();
           this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }
    
    Color navcolor = new Color(153,0,51);
 Color headcolor = new Color(0,51,102);
 Color bodycolor = new Color(153,153,255);  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        v = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        m = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        n = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        v1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(651, 350));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(153, 0, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-profile-100.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 110));

        jPanel1.add(jPanel3);
        jPanel3.setBounds(470, 10, 120, 110);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setText("REAL-ESTATE PROPERTY RECORDING APP");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 40, 430, 50);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Admin");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(510, 120, 50, 17);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-1, 0, 630, 150);

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setLayout(null);

        v.setBackground(new java.awt.Color(153, 153, 255));
        v.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vMouseExited(evt);
            }
        });
        v.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-view-50.png"))); // NOI18N
        v.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 50));

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 10)); // NOI18N
        jLabel4.setText("View Properties");
        v.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 90, -1));

        jPanel2.add(v);
        v.setBounds(100, 50, 100, 90);

        m.setBackground(new java.awt.Color(153, 153, 255));
        m.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mMouseExited(evt);
            }
        });
        m.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-admin-settings-male-50.png"))); // NOI18N
        m.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 50));

        jLabel8.setFont(new java.awt.Font("Yu Gothic", 1, 10)); // NOI18N
        jLabel8.setText("Manage Records");
        m.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 90, 20));

        jPanel2.add(m);
        m.setBounds(250, 50, 100, 90);

        n.setBackground(new java.awt.Color(153, 153, 255));
        n.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nMouseExited(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-log-out-32.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });

        javax.swing.GroupLayout nLayout = new javax.swing.GroupLayout(n);
        n.setLayout(nLayout);
        nLayout.setHorizontalGroup(
            nLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        nLayout.setVerticalGroup(
            nLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(n);
        n.setBounds(560, 140, 40, 40);

        v1.setBackground(new java.awt.Color(153, 153, 255));
        v1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                v1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                v1MouseExited(evt);
            }
        });
        v1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-automatic-50.png"))); // NOI18N
        v1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 50));

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 1, 10)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Settings ");
        v1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 80, -1));

        jPanel2.add(v1);
        v1.setBounds(400, 50, 100, 90);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(-4, 150, 630, 210);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vMouseEntered
        v.setBackground(headcolor);
    }//GEN-LAST:event_vMouseEntered

    private void vMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vMouseExited
        v.setBackground(bodycolor);
    }//GEN-LAST:event_vMouseExited

    private void mMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mMouseEntered
        m.setBackground(headcolor);
    }//GEN-LAST:event_mMouseEntered

    private void mMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mMouseExited
        m.setBackground(bodycolor);
    }//GEN-LAST:event_mMouseExited

    private void vMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vMouseClicked
         view down = new view();
        dtop.add(down).setVisible(true);
    }//GEN-LAST:event_vMouseClicked

    private void mMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mMouseClicked
      Record down = new Record();
        dtop.add(down).setVisible(true);
    }//GEN-LAST:event_mMouseClicked

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        n.setBackground(headcolor);
    }//GEN-LAST:event_jLabel10MouseEntered

    private void nMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nMouseExited
        n.setBackground(bodycolor);
    }//GEN-LAST:event_nMouseExited

    private void nMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nMouseEntered
        n.setBackground(headcolor);
    }//GEN-LAST:event_nMouseEntered

    private void nMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nMouseClicked
       log b= new log ();
        b.setVisible(true);
         b.setDefaultCloseOperation(rep.DISPOSE_ON_CLOSE); 
    }//GEN-LAST:event_nMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked

        this.dispose();
        log b= new log ();
        b.setVisible(true);
         
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        n.setBackground(bodycolor);
    }//GEN-LAST:event_jLabel10MouseExited

    private void v1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_v1MouseClicked

    private void v1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v1MouseEntered
       v1.setBackground(headcolor);
    }//GEN-LAST:event_v1MouseEntered

    private void v1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v1MouseExited
        v1.setBackground(bodycolor);
    }//GEN-LAST:event_v1MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel m;
    private javax.swing.JPanel n;
    private javax.swing.JPanel v;
    private javax.swing.JPanel v1;
    // End of variables declaration//GEN-END:variables
}
